# 任务配置文件
# 定义工作流中的各个任务

# optimize_query_task:
#   description: "根据用户输入和时间序列数据生成精确的搜索查询或提取关键指标。若请求类型为extract_indicator，则从用户查询中提取关键金融指标（如证券名称、商品等）并以格式indicator:{extracted_indicator}返回；若请求类型为optimize_query，则生成优化的搜索查询，必须保持after:DATE before:DATE的时间限制格式，如'why VLCC price decrease after:2024-02-16 before:2025-01-03'。"
#   expected_output: "若提取指标，则返回格式为indicator:{extracted_indicator}；若优化查询，则返回优化后的搜索查询字符串，保持'after:DATE before:DATE'的时间限制格式。所有输出均为英文。"
#   agent: "query_agent"
#   async_execution: false
#   output_file: "{job_id}/queries/{time_period_id}_optimized_query.txt"

search_news_task:
  description: "使用搜索引擎查找与时间段价格变化相关的新闻和信息"
  expected_output: "搜索结果JSON"
  agent: "search_agent"
  async_execution: false
  output_file: "{job_id}/serper/{time_period_id}_search_results.json"

extract_indicator_task:
  description: "从用户查询中提取需要被搜索的主体指标，如果是中文则翻译成英文，返回格式为‘提取的英文指标名’。"
  expected_output: "返回格式为‘提取的英文指标名’，例如’gold price’"
  agent: "query_agent"
  async_execution: false
